.TH FLOW 1

.SH NAME
flow \- creates NetFlow records from pcap file and sends them to the collector

.SH SYNOPSIS
flow [-f <file>] [-c <netflow_collector>[:<port>]] [-a <active_timer>] [-i <inactive_timer>] [-m <count>]

.SH DESCRIPTION
NetFlow exporter that creates NetFlow records from captured network data in pcap format and sends them to the collector

.SH OPTIONS
.TP
.BR \-f " " <file>
Name of the analyzed file or STDIN
.TP
.BR \-c " " <neflow_collector:port> 
The IP address or hostname of the NetFlow collector. Optionally also the UDP port (default 127.0.0.1:2055)
.TP
.BR \-a " " <active_timer>
Interval in seconds after which active records are exported to the collector (default 60)
.TP
.BR \-i " " <seconds>
Interval in seconds after which inactive records are exported to the collector (default 10)
.TP
.BR \-m " " <count>
Flow-cache size. When the maximum size is reached, the oldest record in the cache is exported to the collector (default 1024)

.SH EXAMPLES
.TP
 ./flow -f input.pcap -c 192.168.0.1:2055
Read input from input.pcap and send NetFlow records to collector with ip 192.168.0.1:2055
.TP
 ./flow -f input.pcap -m 10
Read input from input pcap and sets flow-cache size to 10. NetFlow are send to 127.0.0.1:2055.

.SH AUTHOR
.TP 
Vaclav Korvas (xkorva03)